version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./gpu_share.db
      - SECRET_KEY=aigpushare_production_super_secret_key_2026
    volumes:
      - ./backend:/app/backend
      - ./ml/models:/app/ml/models
      - ./ml/datasets:/app/ml/datasets
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped
